enum COLORS {
  YELLOW = '#fdcd01',
  FONT = 'black',
  LINK = '#444',
  LINK_HOVER = 'black',
  BACKGROUND = '#d9d9d9',
  BACKGROUND_FEATURED = 'white',
  BLACK_01 = 'rgba(0, 0, 0, 0.1)',
  BLACK_03 = 'rgba(0, 0, 0, 0.3)',
}

enum PARTS_OF_SPEECH {
  ADJECTIVE = 'ADJECTIVE',
  ADVERB = 'ADVERB',
  CONJUNCTION = 'CONJUNCTION',
  INTERJECTION = 'INTERJECTION',
  NOUN = 'NOUN',
  NUMERAL = 'NUMERAL',
  PARTICIPLE = 'PARTICIPLE',
  PREPOSITION = 'PREPOSITION',
  PRONOUN = 'PRONOUN',
  VERB = 'VERB',
}

enum SUB_PARTS_OF_SPEECH {
  ADJECTIVE_PRONOUN = 'ADJECTIVE_PRONOUN',
  ADVERB = 'ADVERB',
  ADVERB_PRONOUN = 'ADVERB_PRONOUN',
  CONJUGATION_I = 'CONJUGATION_I',
  CONJUGATION_II = 'CONJUGATION_II',
  CONJUGATION_III = 'CONJUGATION_III',
  CONJUGATION_IV = 'CONJUGATION_IV',
  CONJUNCTION = 'CONJUNCTION',
  FEMININE = 'FEMININE',
  INFLECTIV_ADJECTIVE = 'INFLECTIV_ADJECTIVE',
  INFLECTIV_NUMERAL = 'INFLECTIV_NUMERAL',
  INTERJECTION = 'INTERJECTION',
  MASCULINE = 'MASCULINE',
  NEUTER = 'NEUTER',
  NON_MASCULINE = 'NON_MASCULINE',
  NOUN_PRONOUN = 'NOUN_PRONOUN',
  NUMERAL_PRONOUN = 'NUMERAL_PRONOUN',
  PARTICIPLE = 'PARTICIPLE',
  PLURAL_MASCULINE = 'PLURAL_MASCULINE',
  PREPOSITION = 'PREPOSITION',
  UNINFLECTIV_ADJECTIVE = 'UNINFLECTIV_ADJECTIVE',
  UNINFLECTIV_NUMERAL = 'UNINFLECTIV_NUMERAL',
}

enum LOCALES {
  pl = 'pl',
  csb = 'csb',
  en = 'en',
  de = 'de',
  uk = 'uk',
}

export { COLORS, PARTS_OF_SPEECH, SUB_PARTS_OF_SPEECH, LOCALES };
