export const nounVariation = {
  nominative: '',
  nominativePlural: '',
  genitive: '',
  genitivePlural: '',
  dative: '',
  dativePlural: '',
  accusative: '',
  accusativePlural: '',
  instrumental: '',
  instrumentalPlural: '',
  locative: '',
  locativePlural: '',
  vocative: '',
  vocativePlural: '',
};

export const presentVariations = {
  firstPersonSingular: '',
  firstPersonPluralFirst: '',
  firstPersonPluralSecond: '',
  secondPersonSingular: '',
  secondPersonPluralFirst: '',
  secondPersonPluralSecond: '',
  thirdPersonSingular: '',
  thirdPersonPlural: '',
};

export const pastVariations = {
  firstPersonMasculine: '',
  firstPersonFeminine: '',
  firstPersonNeuter: '',
  firstPersonPluralMasculineFirst: '',
  firstPersonNonMasculineFirst: '',
  firstPersonPluralSecondMasculine: '',
  firstPersonPluralSecondNonMasculine: '',
  secondPersonMasculine: '',
  secondPersonFeminine: '',
  secondPersonNeuter: '',
  secondPersonPluralMasculineSecond: '',
  secondPersonNonMasculineSecond: '',
  secondPersonPluralMasculineFirst: '',
  secondPersonNonMasculineFirst: '',
  secondPersonPluralMasculineThird: '',
  secondPersonNonMasculineThird: '',
  thirdPersonMasculine: '',
  thirdPersonFeminine: '',
  thirdPersonNeuter: '',
  thirdPersonPluralMasculine: '',
  thirdPersonNonMasculine: '',
};

export const descriptivePresentVariations = {
  firstPersonMasculine: '',
  firstPersonFeminine: '',
  firstPersonNeuter: '',
  firstPersonPluralMasculineFirst: '',
  firstPersonNonMasculineFirst: '',
  firstPersonPluralMasculineSecond: '',
  firstPersonNonMasculineSecond: '',
  secondPersonMasculine: '',
  secondPersonFeminine: '',
  secondPersonNeuter: '',
  secondPersonPluralMasculineSecond: '',
  secondPersonNonMasculineSecond: '',
  thirdPersonMasculine: '',
  thirdPersonFeminine: '',
  thirdPersonSingular: '',
  secondPersonPluralMasculineFirst: '',
  secondPersonNonMasculineFirst: '',
  thirdPersonPluralMasculine: '',
  thirdPersonNonMasculine: '',
};

export const gerundiumVariations = {
  nominative: '',
  genitive: '',
  dative: '',
  accusative: '',
  instrumental: '',
  locative: '',
  vocative: '',
  nominativePlural: '',
  genitivePlural: '',
  dativePlural: '',
  accusativePlural: '',
  instrumentalPlural: '',
  locativePlural: '',
  vocativePlural: '',
};

export const numeralVariation = {
  nominativeMasculine: '',
  nominativeFeminine: '',
  nominativeNeuter: '',
  genitiveMasculine: '',
  genitiveFeminine: '',
  genitiveNeuter: '',
  dativeMasculine: '',
  dativeFeminine: '',
  dativeNeuter: '',
  accusativeMasculine: '',
  accusativeFeminine: '',
  accusativeNeuter: '',
  instrumentalMasculine: '',
  instrumentalFeminine: '',
  instrumentalNeuter: '',
  locativeMasculine: '',
  locativeFeminine: '',
  locativeNeuter: '',
  vocativeMasculine: '',
  vocativeFeminine: '',
  vocativeNeuter: '',
  nominativePluralMasculine: '',
  nominativeNonMasculine: '',
  genitivePluralMasculine: '',
  genitiveNonMasculine: '',
  dativePluralMasculine: '',
  dativeNonMasculine: '',
  accusativePluralMasculine: '',
  accusativeNonMasculine: '',
  instrumentalPluralMasculine: '',
  instrumentalNonMasculine: '',
  locativePluralMasculine: '',
  locativeNonMasculine: '',
  vocativePluralMasculine: '',
  vocativeNonMasculine: '',
};
